[theme]
primaryColor = "#00C853"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false